FROM mjfryc/centos6-i686-core:v2
RUN linux32 yum -y install gcc cmake cmake git doxygen autoconf bison flex nano wget
RUN linux32 yum -y groupinstall 'Development Tools'

RUN linux32 yum -y install audit-libs-python avahi avahi-libs boost boost-date-time boost-devel boost-filesystem boost-graph boost-iostreams boost-math boost-program-options boost-python boost-regex boost-serialization boost-signals boost-system boost-test boost-thread boost-wave bzip2-devel crash dbus dejagnu environment-modules expect gcc-c++ glibc-static gmp-devel kernel-devel libX11 libX11-common libXau libcgroup libdaemon libgfortran libibumad libibverbs libicu libnl librdmacm libselinux-python libsemanage-python libstdc++-devel libtool-ltdl libxcb lm_sensors-libs mpfr-devel nc numactl openmpi-1.8 opensm-libs papi perl-HTML-Parser perl-HTML-Tagset policycoreutils-python prelink setools-libs setools-libs-python strace tcl unzip xz-devel zip zlib-devel perl-core

